//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiPageApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zakup()
        {
            this.ZakupKomplect = new HashSet<ZakupKomplect>();
        }
    
        public int ID_Zakup { get; set; }
        public int ID_Komplect { get; set; }
        public int ID_Postavshik { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<System.DateTime> Data_zakup { get; set; }
    
        public virtual Postavshik Postavshik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZakupKomplect> ZakupKomplect { get; set; }
    }
}
